{
    'name': 'La Venezolana Seguros',
    'version': '17.0.1.0.0',
    'summary': 'Gestión de Pólizas de Seguros',
    'description': 'Módulo para gestionar pólizas de seguros de La Venezolana',
    'category': 'Insurance',
    'author': 'Tu Nombre',
    'website': 'www.tuempresa.com',
    'license': 'LGPL-3',
    'depends': ['base', 'mail', 'report_xlsx', 'web'],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'data/sequence.xml',
        'views/tomador_views.xml',
        'views/poliza_views.xml',
        'views/vehiculo_views.xml',
        'views/cobertura_views.xml',
        'reports/carnet_rc_report.xml',
        'reports/poliza_report.xml',  # Agregada esta línea
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
}